### ISSUE TITLE
AUI Select2 Error on mounted

### ISSUE THREAD

**Issue by guastallaigor** [spartez/vue-aui#27]
### Versions and Environment
Vue-aui: ^1.0.8
Vue: 2.5.17
Browser: Google Chrome 69.0.3497.100 64 bits
OS: Linux (Ubuntu) 16.04

### Steps to reproduce
Copy the `<va-select2>` from the AUI Select2 Docs.

```html
<va-select2 v-model="selectValue" placeholder="Select value" allow-clear :disabled="initiallyDisabled">
    <va-select2-option value="value1" text="Option 1"></va-select2-option>
    <va-select2-option value="value2" text="Option 2"></va-select2-option>
  </va-select2>
```

### Expected Behavior
Should show the select without any errors.

### Actual Behavior

![image](https://user-images.githubusercontent.com/22016005/47091390-299dbd00-d1fb-11e8-89b4-5f31029a8ff8.png)

### Package.json

![image](https://user-images.githubusercontent.com/22016005/47091517-5fdb3c80-d1fb-11e8-9bed-f964efe4f221.png)

### Main.js

![image](https://user-images.githubusercontent.com/22016005/47091740-d5470d00-d1fb-11e8-9961-d58dea606c86.png)

---

### Additional Comments:
Am I forgetting something? If so I do apologize but I can't find the solution.

**Comment by jwoyo** [comment]
I had the same problem. Luckily I found the reason in the source. Its not a bug in vue-aui. 
The error occures if the jQuery instance on atlassians AUI object isn't extended by the property "auiSelect2".
Atlassians [explains here](https://docs.atlassian.com/aui/7.9.5/docs/auiselect2.html), that you have to require select2-foo on your own.

The web-resource with key com.atlassian.auiplugin:aui-select2 is not available in the context in which you app is loaded. fix this in you atlassian-plugin.xml by adding 
`<dependency>com.atlassian.auiplugin:aui-select2</dependency>`
in the same context as your app.

If you're using [atlassians fancy new webpack-plugin](https://www.npmjs.com/package/atlassian-webresource-webpack-plugin) (recommendation!), add this line, where you use the component: `import "wr-dependency!com.atlassian.auiplugin:aui-select2";`
(this basically does the same as the first solution, it just adds xml-node mentations to the plugin.xml)

**Comment by guastallaigor** [comment]
Thank you @jwoyo for your reply. You're right, I wan't importing it.
I looked into vue-aui's source, and found this imports:
```javascript
import "@atlassian/aui/dist/aui/css/aui.min.css"
import "@atlassian/aui/dist/aui/css/aui-experimental.min.css"
import "@atlassian/aui/dist/aui/js/aui-experimental.min"
import "@atlassian/aui/dist/aui/js/aui-datepicker.min"
import "@atlassian/aui/dist/aui/js/aui-soy.min"
```
And now it works. I will look into the atlassians webpack plugin that you recommended. But for now it's working, so I'm closing this. Thank you again.

**Comment by hellboy81** [comment]
@jwoyo: If I use  new atlassian `webpack-plugin`:  should I add each time `<dependency>com.atlassian.auiplugin:aui-select2</dependency>` to generated xml manually?

**Comment by jwoyo** [comment]
It's not necessary to edit the generated file. Using this line 
`import 'wr-dependency!com.atlassian.auiplugin:dialog2';`
in any .js (or .ts or .vue) file will add the dependency node you mentioned above automatically to the xml. You will find the xml in the folder you specified using the "xmlDescriptors" prop when creating "WrmPlugin" in your webpack.config.
