### ISSUE TITLE
[Feature request] Striped prop to VaTable

### ISSUE THREAD

**Issue by guastallaigor** [spartez/vue-aui#31]
### What problem does this feature solve?
Striped or "zebra" rows kind of like [Bootstrap Striped Rows](https://getbootstrap.com/docs/4.1/content/tables/#striped-rows).

### What is your proposed solution?

1.Passing a new prop, which the default is false:

```javascript
striped: Boolean
```

2.Add a class or style that changes the background-color to some grey color like #d9d9d9 (not sure yet).

3.This class is added to every even row when striped is true.

**Comment by damienix** [comment]
TBH I'm quite reluctant to this request. I'm browsing Atlassian patterns

https://docs.atlassian.com/aui/7.9.9/docs/tables.html
https://atlaskit.atlassian.com/packages/core/table-tree
https://atlassian.design/guidelines/product/components/tables

And Atlassian doesn't really have any similar pattern in their design language. This should probably be quite easy to add from outside anyway... It's also a major design change comparing to other requests that e.g. add a custom color.

Let me know if you really thing this should be added for some reason.

**Comment by guastallaigor** [comment]
I understand your point of view and I agree with that so I'm dropping it.
