### ISSUE TITLE
[Feature request] New component: Timeline.

### ISSUE THREAD

**Issue by guastallaigor** [spartez/vue-aui#37]
**This is not an AUI feature.**

### What problem does this feature solve?
Add a new timeline component kind of like [this](https://vuetifyjs.com/en/components/timelines#introduction).

### What is your proposed solution?

1.This timeline at first must be centered (full-width) but responsive. User pass the array of object, kind of like VaTable, with title and content attributes. Some other props to align content/title and set the color. Maybe some more props to change the text color.

```javascript
items: Array,
alignContent: String,
alignTitle: String,
color: String
...
```

2.Must have some events like click that returns the object clicked and some hover effects.

**Basic draft:**

![image](https://user-images.githubusercontent.com/22016005/48963371-127b8900-ef78-11e8-96fb-972308d2c0df.png)

2.It will use the same classes or similar to AUI's.

-------------------------

**Note:** If you don't want this that's fine, but if you think it is a good idea and if you have some suggestions please let me know. Thank you.

**Comment by damienix** [comment]
I don't think I have any strong suggestions. I think it could be added to this library provided that it doesn't stand out from AUI in style.

**Comment by guastallaigor** [comment]
I will have to do some research regarding AUI's style on this, so I'm closing this issue for now.
